#!/bin/bash
set -x
rm -rf vendor/{zlib,htslib,googletest}
rm -f CMakeCache.txt
rm -f DartConfiguration.tcl
rm -f src/config.h
rm -f pcr
rm -f libunitylib.a libpcrlib.a
rm -rf googletest-*
rm -rf vendor/
rm -f src/test/test_match
find -type d -path '*CMakeFiles*' -print0 | xargs -0 rm -rf
find -type d -path '*Testing*' -print0 | xargs -0 rm -rf
find -name '*.cmake' -and -not -name 'google_test.cmake' -print0 | xargs -0 rm -f
find -name Makefile -print0 | xargs -0 rm -f
